README.md, pygitguardian/__init__.py
- Fixes `README` examples
- Bump version for next release while CI is not configured
=> fix(docs): fix README examples

README.md
Adds small introduction detailing API and `py-gitguardian`'s possibilities
=> fix(doc): add API introduction to README

.pre-commit-config.yaml, Pipfile.lock, pygitguardian/__init__.py, pygitguardian/client.py, tests/test_client.py
- Load non json errors as details if possible
=> Make non json errors more explicit

.pre-commit-config.yaml, Pipfile, Pipfile.lock, pygitguardian/client.py, pygitguardian/models.py, tests/cassettes/quota.yaml, tests/test_client.py
- Add Quota overview route `/v1/quotas` to client
=> feat(quotas): add quota route

Pipfile.lock, pygitguardian/models.py, tests/cassettes/test_health_check_error.yaml, tests/test_client.py
- Convert error to detail on failed response
=> fix(detail): convert error to detail

.github/workflows/test-lint.yml, .gitlab-ci.yml, .pre-commit-config.yaml, .prettierrc, Pipfile, Pipfile.lock, examples/content_scan.py, examples/directory_scan.py, pygitguardian/__init__.py, pygitguardian/client.py, pygitguardian/models.py, pyproject.toml, setup.py, tests/cassettes/filename.yaml, tests/cassettes/filename_secret.yaml, tests/cassettes/max_size_array.yaml, tests/cassettes/no_breaks.yaml, tests/cassettes/quota.yaml, tests/cassettes/secret.yaml, tests/cassettes/test_assert_content_type.yaml, tests/cassettes/test_content_not_ok.yaml, tests/cassettes/test_health_check.yaml, tests/cassettes/test_health_check_error.yaml, tests/cassettes/test_multi_content_not_ok.yaml, tests/cassettes/with_breaks.yaml
- Bring standards from ggshield to pygitguardian
=> chore(pygitguardian): remove old python version support.

pygitguardian/models.py, tests/cassettes/secret_validity.yaml, tests/test_client.py
Include validity in scan output
=> Include validity in scan output

Pipfile, pygitguardian/client.py, pygitguardian/iac_models.py, tests/test_iac_models.py, tests/test_utils.py
Transfered `IaCGGClient` from `ggshield` to here.
Closes: https://github.com/GitGuardian/ggshield/issues/405
=> feat: added iac models and modified GGClient

.github/workflows/test-lint.yml, pygitguardian/client.py, pygitguardian/models.py, setup.py, tests/test_client.py
This is py-gitguardian version of https://github.com/GitGuardian/ggshield/pull/491.
- chore: run pyupgrade
- chore: update actions/checkout to v3
=> Spring cleanup

changelog.d/20230425_100744_antonin.lacombe_implement_honeytoken_creation.md, pygitguardian/client.py, pygitguardian/models.py, tests/test_client.py, tests/test_models.py
Add create honeytoken feature with marshmallow models
=> implement `create_honeytoken` method

changelog.d/20230505_162227_antonin.lacombe_update_honeytoken_id_type.md, pygitguardian/models.py, tests/test_client.py, tests/test_models.py
Add `gitguardian_url` and change id type of `honeytoken`'s model
=> Update Honeytoken model

.github/workflows/test-lint.yml, Makefile, changelog.d/20230425_100744_antonin.lacombe_implement_honeytoken_creation.md, changelog.d/20230505_162227_antonin.lacombe_update_honeytoken_id_type.md, pygitguardian/client.py, pygitguardian/models.py, tests/test_client.py, tests/test_models.py
This PR makes the CI check the code passes all pre-commit checks, like what is done for GGShield.
Since this was left unchecked for a while, it also fixes a few issues.
=> Enforce precommits

Pipfile
- Pin `vcrpy` to avoid a bug in the latest release.
=> Update and fix vcrpy

.pre-commit-config.yaml
Update GGShield in the pre-commit configuration
=> chore(pre-commit): # update to latest GGShield

.pre-commit-config.yaml
=> chore(pre-commit): update to latest ggshield

pygitguardian/models.py, pyproject.toml
Pyright settings were a bit lax. Tighten them.
=> Enable more type checks

pygitguardian/sca_models.py
Export SCA scan schemas in addition of their dataclasses.
=> feat(sca): export scan schemas in addition of dataclasses

pygitguardian/models.py
Describe what each field of Match represents.
=> Improve Match docstring

.pre-commit-config.yaml
=> Update to latest ggshield

.pre-commit-config.yaml
Update pre-commit to ggshield 1.31.0
=> chore(pre-commit): update to ggshield 1.31.0

.pre-commit-config.yaml
=> Update to ggshield 1.32.0

.pre-commit-config.yaml
=> Update to ggshield 1.33.0

.pre-commit-config.yaml
Fix stage names, update pre-commit-hooks version to fix stage names there.
=> Fix pre-commit warnings

.pre-commit-config.yaml
=> Update to ggshield 1.34.0

changelog.d/20250702_102756_achille.mascia_nhi_ggshield_v2.md, pygitguardian/models.py, tests/test_models.py
Added fields for NNHI ggshield v2
=> chore(nhi): add vault related attributes to PoliyBreak model

.pre-commit-config.yaml
=> Update to ggshield 1.43.0
