GitGuardian/py-gitguardian

- pygitguardian/client.py
- tests/test_client.py
Because of the way `urllib.parse.urljoin` works, if the base URI didn't have a tailing `/`, the path would be truncated.
E.g. `https://onprem.company.com/exposed` with the enpoint `scan` (and version `v1`) would call `https://onprem.company.com/v1/scan` and not `https://onprem.company.com/exposed/v1/scan`.
> fix: base URI without tailing /

- pygitguardian/models.py
Some variables set as optional were not optional. This was catched on an error using ggshield. 
```
ggshield scan path sample.xml
Traceback (most recent call last):
File "/home/sofiengg/.local/lib/python3.8/site-packages/ggshield/dev_scan.py", line 169, in path_cmd
results = files.scan(
File "/home/sofiengg/.local/lib/python3.8/site-packages/ggshield/scan/scannable.py", line 139, in scan
scan = future.result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
raise self._exception
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File …
```
> fix(models): make optional variables optional

- pygitguardian/client.py
- tests/test_client.py
This PR helps catching puzzling errors for ggshield users, where their API key contains non-Latin-1 characters. You can find the details and the puzzling error message here: https://github.com/GitGuardian/ggshield/issues/101.
Since the `GGClient.__init__()` can already raise a `ValueError` for invalid URLs, I opted to do the same for this case.
> fix(ggclient): check API key encoding early

- .github/workflows/test-lint.yml
- pygitguardian/models.py
- tests/test_models.py
This PR makes two fixes:
First it fixes a marshmallow warning about using kwargs arguments to declare fields:
>../../.local/share/virtualenvs/py-gitguardian-n9b0MJaw/lib/python3.8/site-packages/marshmallow/fields.py:218
/home/agateau/.local/share/virtualenvs/py-gitguardian-n9b0MJaw/lib/python3.8/site-packages/marshmallow/fields.py:218: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'validates': <Length(min=1, max=None, equal=None, error=None)>}
Turns out it was a typo.
Second, it fixes the CI to really run tests on all OS. Hopefully this is less involved than for ggshield (https://github.com/GitGuardian/ggshield/pull/164).
> Some small fixes

- pygitguardian/client.py
- pygitguardian/models.py
- tests/cassettes/document_with_0_bytes.yaml
- tests/test_client.py
- tests/test_models.py
> Replace 0 bytes in document instead of raising an exception

- .github/workflows/changelog-check.yml
- .github/workflows/test-lint.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Pipfile
- changelog.d/20230327_152427_aurelien.gateau_setup_scriv.md
- changelog.d/README.md
- pyproject.toml
- scripts/release
- tests/conftest.py
- tests/test_client.py
After these changes, contributors have to use `scriv create` to create changelog fragments. The CI enforces this is the case. One can apply the `skip-changelog` label to pull requests which do not require a changelog fragment (see the latest changes in CONTRIBUTING.md for details).
At release time, the `scripts/release` script uses `scriv` to update the changelog and fill the GitHub release notes.
This is py-gitguardian version of https://github.com/GitGuardian/ggshield/pull/499.
> Add a CHANGELOG

- changelog.d/20230403_154257_alina.tuholukova_include_incident_url.md
- pygitguardian/models.py
- tests/test_models.py
incident_url is included when the secret of a policy break is known by a dashboard
> feat(api): parse incident_url from the multiscan endpoint

- Pipfile
vcrpy does not use urllib3 correctly. Pin urllib3 until https://github.com/kevin1024/vcrpy/issues/688 is fixed.
> Fix test failure caused by vcrpy

- .github/workflows/test-lint.yml
- Pipfile
- pygitguardian/models.py
- tests/test_client.py
This PR does some house-keeping in py-gitguardian tests:
Switch to [responses](https://pypi.org/project/responses/) to mock `requests` responses. This makes mocks closer to the real classes than our home-made mocks. It was required by an upcoming change to make `GGClient.request()` log the received HTTP status code. Adding this log caused the tests to fail because the mocked responses did not have a `status_code` field.
Fix a Marshmallow deprecation warning in the tests:
```
../../.local/share/virtualenvs/py-gitguardian-n9b0MJaw/lib/python3.10/site-packages/marshmallow/fields.py:1571
/home/agateau/.local/share/virtualenvs/py-gitguardian-n9b0MJaw/lib/python3.10/site-packages/marshmallow/fields.py:1571: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. …
```
> Improve tests

- changelog.d/20230529_153802_aurelien.gateau_log.md
- pygitguardian/client.py
For each request, log the HTTP method, endpoint, status code and duration.
This should help when investigating network issues.
> Log all HTTP requests

- .github/workflows/test-lint.yml
- .pre-commit-config.yaml
- MANIFEST.in
- Pipfile
- pygitguardian/client.py
- pygitguardian/iac_models.py
- pygitguardian/models.py
- pygitguardian/py.typed
- pyproject.toml
- setup.py
This PR improves type-safety by doing two things:
Switches to pyright, which catches more errors. As a result I had to introduce 2 mixins to make Marshmallow code more type-safe: `FromDictMixin` provides a `from_dict()` method, `ToDictMixin` provides the matching `to_dict()` method.
Code which previously deserialized objects using `<Class>.SCHEMA.load(dct)` now use `<Class>.from_dict(dct)`.
`Base` inherits from `ToDictMixin`, but not from `FromDictMixin` because unfortunately some of our classes do not deserialize to objects and changing that would break API compatibility. This is the case for `Document` and `HealthCheckResponse`.
Installs a `py.typed` marker file so that type-checkers running on packages using py-gitguardian knows the package has type-hints.
> Switch to pyright, complete type-hinting

- changelog.d/20230622_100420_sylvain.baud.ext_fix_request_data_field.md
- pygitguardian/client.py
GGClient `iac_directory_scan` method called the GGClient `post` method with the argument `data`.
It expected the data argument to be used in request .request with a key `data`. 
However post processed the `data` argument and used it in request.request with a key `json`.
Therefore I renamed the argument `data` to `json` to avoid confusion and free the `data` argument to be used with the `data` key.
> fix: change request param to accept data

- changelog.d/20230712_172917_aurelien.gateau_fix_maximum_size_check.md
- pygitguardian/client.py
- pygitguardian/models.py
- tests/test_models.py
The Unicode replacement character becomes 2 bytes in UTF-8 (0xFF 0xFD). Replacing \0 with this character causes the encoded string to be one byte longer, making it possible for the encoded document to be longer than the maximum document size.
Use the ASCII substitute character instead: it's only 1 byte long in UTF-8, so it does not make the encoded document grow.
This is going to help with https://github.com/GitGuardian/ggshield/issues/561.
> Do not make the encoded document larger than expected

- pygitguardian/iac_models.py
The scan result received from the API now may include additional vulnerability data, based on their status on the GitGuardian dashboard.
> feat(iac): update iac scan result model with new fields from API

- .github/workflows/test-lint.yml
Similar to ggshield:
- block merges on fixup commits
- update actions/checkout to v4
- drop Python 3.7 (already done for quite some time on ggshield)
> CI improvements

- changelog.d/20231221_170806_aurelien.gateau_report_rate_limit.md
- pygitguardian/__init__.py
- pygitguardian/client.py
- tests/conftest.py
- tests/test_client.py
We want to apply rate-limits to the GitGuardian server endpoints used by GGShield. To be able to do so, py-gitguardian must be able to:
- identify a rate-limit error
- wait the appropriate delay and retry
- notify callers that we are rate-limited
This PR introduces a new abstract class, `GGClientCallbacks`. A caller interested in getting notified of rate-limit events must:
- Implement the `GGClientCallbacks` abstract class
- Pass an instance of it when creating a `GGClient` instance
> Handle API rate-limits

- .github/workflows/test-lint.yml
Do not run GGShield on PR from forks: it fails because GITGUARDIAN_API_KEY is not set in this case.
> Avoid lint fail on PR from forks

- .github/workflows/test-lint.yml
Minor CI fixes following the release:
- Update some GitHub actions to the latest version (and pin pypa/gh-action-pypi-publish which was still using master, which is deprecated)
- Add Python 3.12 to our test matrix
> Post-release fixes

- .github/workflows/test-lint.yml
Tested in my sandbox repository: https://github.com/agateau-gg/ci-sandbox/pull/4
> Fix fixup commit message checker failing on PR from forks

- pygitguardian/sca_models.py
- tests/test_sca_models.py
Issue: SCA-1345
- Adds `ignore_no_fix` and `ignore_fix_available` scan parameters in SCA models.
> feat(sca): add input scan parameters to ignore vulns

- pygitguardian/sca_models.py
Update SCA scan results models to match the new API's fields used for the autoignore feature.
> feat(sca): update sca scan result model with new fields from API

- changelog.d/20240514_143905_aurelien.gateau_improve_error_handling.md
- pygitguardian/client.py
- tests/test_client.py
This PR improves how we handle server responses by not assuming it is going to include a `Content-Type` header. This makes GGClient more robust in contexts where network responses are generated by tools like firewalls.
> Improve error handling

- .github/workflows/test-lint.yml
- changelog.d/20240624_103236_aurelien.gateau_fix_release_job.md
Now that py-gitguardian uses pdm, it no longer has a setup.py. This caused the "release" job to fail.
Switch to using `build` to create the release sdist and wheel.
Tested by adding a fake release job which ran the same commands as the "release" job. The result of the fake job can be seen [here](https://github.com/GitGuardian/py-gitguardian/actions/runs/9642297578/job/26589890381), but it was created in a separate commit which I have now reverted.
> Fix release job

- pyproject.toml
Do not hardcode version number in pyproject.toml: read it from `pygitguardian/__init__.py` instead.
This caused the [release to fail](https://github.com/GitGuardian/py-gitguardian/actions/runs/9642972539/job/26592043917) because it created a 1.14.0 wheel.
Should have caught that in the previous fix 🤦🏻.
> Fix release step using wrong version number

- changelog.d/20240701_180056_fnareoh_scrt_4626_ggshield_display_custom_remediation_message_in_ggshield_if.md
- pygitguardian/client.py
- pygitguardian/config.py
- pygitguardian/models.py
- tests/test_client.py
This MR add a new dataclass `RemediationMessages` used in the `GGClient` to store information given by the metadata endpoint and if the remediation message are not part of the API answer the default are used.
This change is meant to be used with https://github.com/GitGuardian/ggshield/pull/928 .
> Add remediation messages to GGclient

- changelog.d/20241014_101918_mathias.millet_handle_excluded_policy_breaks.md
- pygitguardian/client.py
- pygitguardian/models.py
- tests/test_client.py
- tests/test_models.py
-  fix `load_default` for `incident_url`  (`None` instead of `False`)
- Handle two new fields in PolicyBreaks, that will be returned by the scan routes.
A bit bothered by using two fields, but using a single `exclude_reason` does not seem right either.
> handle excluded policy breaks

- changelog.d/20241107_113401_pierrelalanne_fix_typing_issue_on_severity.md
- pygitguardian/models.py
This had been forgotten in the original implementation. See corresponding MR in ggshield to use this version of py-gitguardian until a new version is released.
This PR solves #120
> Add info as a possible value for Severity

- changelog.d/20241113_094144_samuel.guillaume_spi_526_add_fields_is_diff_and_diff_kind.md
- pygitguardian/models.py
- tests/test_models.py
Add two new fields to the result of scans:
- Add field `is_diff` to `ScanResult`
- Add field `diff_kind` to `PolicyBreak`
> feat(models): Add is_diff to ScanResult and diff_kind to PolicyBreak

- .gitguardian.yml
- changelog.d/20241120_112255_salome.voltz_add_api_tokens_endpoint_method.md
- pygitguardian/client.py
- pygitguardian/models.py
- tests/test_client.py
- tests/test_models.py
`GGClient` now provides a `api_tokens()` method to retrieve API token details (see https://api.gitguardian.com/docs#tag/API-Tokens).
`api_tokens()` can be called with a token to retrieve its details or without argument to retrieve the current token details.
Note: best reviewed commit-by-commit. First commit updates the .gitguardian.yaml to remove deprecated keys.
> Add api_tokens() method to retrieve API token details 

- pygitguardian/client.py
- pygitguardian/models.py
- tests/test_client.py
- tests/test_models.py
While reviewing the ggshield PR to check for tokens I realized two naming inconsistencies were merged here. This PR fixes them before we release:
- TokenScopes -> TokenScope: because enum names should be singular
- ApiToken* -> APIToken*: because PEP 8 says so. Also, this is more consistent with other classes of the package (`JWTService`, `JWTResponse`...)
> Pre-release renames

- scripts/release
- scripts/setup_test_workspace.py
- tests/cassettes/test_create_team_invitation.yaml
- tests/cassettes/test_create_team_member.yaml
- tests/test_client.py
This PR introduces a script that will attempt to setup the workspace used for running tests without relying on cassettes reliably. It also loosens some constraint on the test to make the workspace slightly easier to setup.
There are a few limitations imposed by the API that prevents the workspace from being completely setup, a notice has been added at the top of the script, those limitations are :
- We cannot create members, so there must exist a minimum amount of members in the workspace
- This also means deleted members cannot be brought back from the script
- We cannot integrate a source entirely from the public API
- There must exist a source in the workspace
The script relies on the following environment variables:
- `GITGUARDIAN_API_KEY` : The PAT or SAT used to authenticate to …
> Implement script to setup workspace for tests

- changelog.d/20250416_142945_salome.voltz_scrt_5438_ggshield_for_each_detected_secret_add_a_link_towards_our.md
- pygitguardian/models.py
- tests/cassettes/secret.yaml
- tests/cassettes/secret_validity.yaml
- tests/cassettes/with_breaks.yaml
- tests/test_client.py
- tests/test_models.py
Add detector infos to scan results: 
- detector name (only the display name was given)
- detector group name
- documentation URL
> feat(scan_results): Add detector infos to scan resutls

- changelog.d/20250425_135326_salome.voltz.md
- pygitguardian/models.py
- tests/test_models.py
This fixes a bug in ggshield. 
When trying to scan somthing with flag `--with-incident-details`, ggshield performs a call to `/api_tokens/{token}`. The response is deserialized using an enum for scopes. 
The enum was missing some recently added scope. Thus, `ggshield secret scan path FILE --with-incident-details` was crashing when called with a token having the new scopes :
> fix: Add missing scopes to TokenScope enum
